feat(django 3): Updates to use with django 3.
sailoboats/django-generic-confirmation pull request #2
Opened 2022-05-20 21:53 UTC by Savchenko-Ilia

## The issue

https://sailo1.atlassian.net/browse/SPM-5373

## The checklist

- [ ] I have performed self-review of my own code
- [ ] I have tested my code locally
- [ ] I have added automatic tests that prove my solution
- [ ] I have made sure the tests cover 85% of the new code
- [ ] I have added type hints to the new code
- [ ] I have made the corresponding changes to the README
- [ ] I have assigned one of my peers to review the code
- [ ] I have tagged the PR accordingly e.g. bug, feat, wip, ready etc.
- [ ] I have specified the sprint this PR corresponds to

2022-05-23 11:23 UTC, alexei requested changes

2022-05-23 11:23 UTC, alexei commented on tox.ini
> +deps = django>=3.0,<3.2.13
To stay in line with the other configs, this should probably say:

```suggestion
deps = django>=3.0,<3.2.99
```

Also don't forget about the new line.

2022-05-23 11:24 UTC, alexei commented
Is it possible to set it up to run tests on GitHub?

2022-05-23 12:14 UTC, Savchenko-Ilia commented
> Is it possible to set it up to run tests on GitHub?

will try

2022-05-25 12:16 UTC, Savchenko-Ilia commented
> Is it possible to set it up to run tests on GitHub?

Done
https://github.com/sailoboats/django-generic-confirmation/pull/2/commits/48a3a0182a5efc4c2b980bac22e2fcbbb00444ad

2022-06-03 09:12 UTC, Savchenko-Ilia commented
@alexei can we merge this ?

2022-06-03 10:41 UTC, alexei commented
> @alexei can we merge this ?

I didn't notice you were done, sorry

2022-06-03 10:41 UTC, alexei approved these changes

2022-06-03 10:41 UTC, merged